baseURL = 'https://poronesia.com/'
languageCode = 'en-us'
title = 'Poronesia Design Solution'
theme = 'poronew'

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

# Default site wide settings
[build.processing]
  skip_processing = true

# Branch specific settings
[context.branch-name.processing]
  skip_processing = false
[context.branch-name.processing.css]
  bundle = false
  minify = true